<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ProPDF.Engine.PdfPig/ProPDF.Engine.PdfPig.csproj" />
    <ProjectReference Include="../../src/ProPDF.Editing/ProPDF.Editing.csproj" />
    <ProjectReference Include="../../src/ProPDF.Presentation/ProPDF.Presentation.csproj" />
  </ItemGroup>
</Project>
