<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ProPDF.SampleSupport/ProPDF.SampleSupport.csproj" />
    <ProjectReference Include="../../src/ProPDF.Avalonia/ProPDF.Avalonia.csproj" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" />
  </ItemGroup>
</Project>
