<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ProPDF.Core/ProPDF.Core.csproj" />
    <ProjectReference Include="../../src/ProPDF.Rendering.Skia/ProPDF.Rendering.Skia.csproj" />
    <ProjectReference Include="../../src/ProPDF.Engine.PdfPig/ProPDF.Engine.PdfPig.csproj" />
    <ProjectReference Include="../../src/ProPDF.Editing.iText/ProPDF.Editing.iText.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" />
  </ItemGroup>
</Project>
